version: '3.3'

services:
    db:
      image: mysql:5.7
      container_name: db
      restart: unless-stopped
      env_file: .env
      environment:
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        MYSQL_DATABASE: $DB_DATABASE
      ports:
        - $DB_PORT:$DB_PORT
      volumes:
        - db_data:/var/lib/mysql
    app:
      build: .
      restart: unless-stopped
      env_file: .env
      ports:
        - 3000:3000
      environment:
         - DB_HOST=db
         - PORT=$NODE_PORT
      depends_on:
         - db
volumes:
  db_data: {}