version: '3.3'

services:
    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      env_file: .env
      environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT
      volumes:
        - db:/var/lib/mysql
    app:
      build: .
      restart: unless-stopped
      env_file: .env
      ports:
        - 3000:3000
      environment:
         - DB_HOST=mysqldb
         - PORT=$NODE_PORT
         - DB_PORT=$MYSQLDB_DOCKER_PORT
      depends_on:
         - mysqldb
volumes:
  db: