version: '3.3'

services:
    db:
      image: mysql:5.7
      container_name: db
      restart: unless-stopped
      env_file: .env
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_HOST: '%'
      ports:
        - $DB_PORT:$DB_PORT
      volumes:
        - db:/var/lib/mysql
    app:
      build: .
      restart: always
      env_file: .env
      ports:
        - 3000:3000
      environment:
         - DB_HOST=db
         - PORT=$NODE_PORT
      depends_on:
         - db
    phpmyadmin:
     image: phpmyadmin
     container_name: pma
     restart: always
     ports:
       - "8080:80"
     environment:
       PMA_ARBITRARY: 1
       PMA_HOST: db
volumes:
   db: